from pathlib import Path


"""全局配置模块。

这个文件集中保存资源路径、窗口尺寸、角色速度、战斗数值等常量。把这些值放在
同一个文件里，方便答辩时说明“地图、图片、音频从哪里加载”，也方便后续调参数。
"""

# 项目根目录和资源根目录。
BASE_DIR = Path(__file__).resolve().parent.parent
RESOURCE_DIR = BASE_DIR / "resource"

# 三张主要地图：村庄、郊外、寺庙。TEMPLE_FALLBACK_MAP_PATH 是寺庙备用地图。
VILLAGE_MAP_PATH = RESOURCE_DIR / "tmx" / "village1.tmx"
OUTSKIRTS_MAP_PATH = RESOURCE_DIR / "tmx" / "scene.tmx"
TEMPLE_MAP_PATH = RESOURCE_DIR / "tmx" / "temple1.tmx"
TEMPLE_FALLBACK_MAP_PATH = RESOURCE_DIR / "tmx" / "temple.tmx"
MAP_PATH = VILLAGE_MAP_PATH

# 人物、NPC、怪物、特效、UI 图片资源路径。
SWK_DIR = RESOURCE_DIR / "img" / "swk"
SWK2_DIR = RESOURCE_DIR / "img" / "swk2"
ELDER_DIR = RESOURCE_DIR / "img" / "elder"
GOD_DIR = RESOURCE_DIR / "img" / "god"
CATTLE_IMAGE_PATH = RESOURCE_DIR / "img" / "cattle" / "station" / "1644-a85e8726-00000.tga"
CATTLE_BACK_DIR = RESOURCE_DIR / "img" / "cattle" / "back"
CATTLE_STATION_DIR = RESOURCE_DIR / "img" / "cattle" / "station"
CATTLE_LOOK_DIR = RESOURCE_DIR / "img" / "cattle" / "look"
CATTLE_RUN_DIR = RESOURCE_DIR / "img" / "cattle" / "run"
CATTLE_WALK1_DIR = RESOURCE_DIR / "img" / "cattle" / "walk1"
CATTLE_WALK2_DIR = RESOURCE_DIR / "img" / "cattle" / "walk2"
CATTLE_FIGHT_DIR = RESOURCE_DIR / "img" / "cattle" / "fight"
CATTLE_DIE_DIR = RESOURCE_DIR / "img" / "cattle" / "die"
MAGIC_APPEAR_DIR = RESOURCE_DIR / "img" / "magic" / "appear"
MAGIC_DISAPPEAR_DIR = RESOURCE_DIR / "img" / "magic" / "disappear"
DIALOG_IMAGE_PATH = RESOURCE_DIR / "img" / "dialog" / "dialog.png"
START_BACKGROUND_PATH = RESOURCE_DIR / "img" / "pic.jpg"
OK_BUTTON_PATH = RESOURCE_DIR / "img" / "button" / "ok.png"
NO_BUTTON_PATH = RESOURCE_DIR / "img" / "button" / "no.png"
SMALL_TEMPLE_BUTTON_PATH = RESOURCE_DIR / "img" / "button" / "temple_button.png"
VILLAGE_BUTTON_PATH = RESOURCE_DIR / "img" / "village_button.png"
TEMPLE_BUTTON_PATH = RESOURCE_DIR / "img" / "temple_button.png"
WIN_IMAGE_PATH = RESOURCE_DIR / "img" / "win.jpg"
FAIL_IMAGE_PATH = RESOURCE_DIR / "img" / "fail.jpg"
FONT_PATH = RESOURCE_DIR / "font" / "newfont.TTF"
BACKGROUND_MUSIC_PATH = RESOURCE_DIR / "sound" / "nmw.mp3"
ATTACK_SOUND_PATH = RESOURCE_DIR / "sound" / "swk.wav"
VICTORY_SOUND_PATH = RESOURCE_DIR / "sound" / "aigei.mp3"

# 窗口与基础运行参数。
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

FPS = 60

# 玩家移动、碰撞和出生点配置。
PLAYER_SPEED = 220
PLAYER_SCALE = 0.5
PLAYER_HITBOX_SIZE = (32, 28)
DEFAULT_PLAYER_SPAWN = (400, 300)
DEFAULT_OUTSKIRTS_SPAWN = (96, 384)
OUTSKIRTS_EXIT_BAND = 96
DEFAULT_TEMPLE_SPAWN = (300, 900)

# NPC 读取层、交互范围和待机动画参数。
NPC_INTERACTION_PADDING = 40
NPC_LAYERS = ("god", "elder", "child")
NPC_IDLE_FRAME_LIMIT = 10
NPC_IDLE_FRAME_TIME = 0.2

# 怪物探索状态、巡逻、追击和动画参数。
MONSTER_LAYERS = ("monster",)
MONSTER_SCALE = 0.75
MONSTER_TRIGGER_PADDING = 12
MONSTER_LOOK_PADDING = 140
MONSTER_PATROL_SPEED = 60
MONSTER_CHASE_SPEED = 105
MONSTER_PATROL_RADIUS = 96
MONSTER_PATROL_MOVE_TIME = 1.5
MONSTER_PATROL_PAUSE_TIME = 1.0
MONSTER_CHASE_LEASH = 260

# 战斗数值和孙悟空 swk2 攻击动画参数。
PLAYER_MAX_HEALTH = 100
SWK2_ATTACK_FRAME_START = 33
SWK2_ATTACK_FRAME_COUNT = 8
SWK2_ATTACK_FRAME_TIME = 0.07
SWK2_BATTLE_SCALE = 1.45
MONSTER_MAX_HEALTH = 60
PLAYER_NORMAL_ATTACK_DAMAGE = 20
PLAYER_SKILL_DAMAGE = 35
PLAYER_SKILL_COOLDOWN_TURNS = 2
PLAYER_ATTACK_DAMAGE = PLAYER_NORMAL_ATTACK_DAMAGE
MONSTER_ATTACK_DAMAGE = 15
DEFEND_DAMAGE_RATE = 0.5
MONSTER_ATTACK_COOLDOWN = 1.6
MONSTER_FIRST_ATTACK_DELAY = 1.3
BATTLE_HIT_FLASH_TIME = 0.35
BATTLE_VICTORY_SECONDS = 1.2

# Boss 牛魔王数值。
BOSS_MAX_HEALTH = 160
BOSS_SCALE = 1.05
BOSS_ATTACK_DAMAGE = 16
BOSS_ATTACK_COOLDOWN = 1.5
BOSS_ENRAGED_ATTACK_DAMAGE = 24
BOSS_ENRAGED_ATTACK_COOLDOWN = 1.0
BOSS_ENRAGE_HEALTH_RATIO = 0.5
BOSS_BANNER_SECONDS = 2.2

# 动画帧率、特效时长和音量。
MONSTER_ANIMATION_FRAME_LIMIT = 8
MONSTER_ANIMATION_FRAME_TIME = 0.12
BATTLE_EFFECT_FRAME_LIMIT = 8
BATTLE_EFFECT_FRAME_TIME = 0.06
MONSTER_DISAPPEAR_FRAME_LIMIT = 10
MONSTER_DISAPPEAR_FRAME_TIME = 0.06
MUSIC_VOLUME = 0.35
SOUND_VOLUME = 0.55
